### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by mladnicholas** [chatziko/FlashSocket.IO#1]
I set up the SSL.CRT and i host the server on cloud9.io but i get a security error. Any help?
It connects and works from flash but when i test it outside flash as a swf it doesn't work.

**Comment by chatziko** [comment]
Hello, I'm willing to provide some support for this project, but only for issues that can be reproduced using the provided sample server and client. If you can reproduce it, send me the sample server/client with your modifications reproducing the problem and I'll have a look (in your case it means that I'll also need the private key of whatever certificate you're using, but you don't need to use the real one of course).

**Comment by mladnicholas** [comment]
Thanks for the reply, But me and my friend were figuring it out all day and
we found a solution. Thanks anyway!

**Comment by chatziko** [comment]
Great, so I'm closing this.
Feel free to send a PR if you had to make changes to FlashSocket.IO itself.

**Comment by mladnicholas** [comment]
Hi, I have a problem now... Well somekind of problem. When I test in Flash
everything works fast and great. When i upload it to a website its kinda
slow (a lot of delays). Any help?
